licenses(["notice"])

package(default_visibility=[])

cc_library(
    name = "ir",
    srcs = [
        "lib/ir/basic_block.cc",
        "lib/ir/builder.cc",
        "lib/ir/constant.cc",
        "lib/ir/context.cc",
        "lib/ir/function.cc",
        "lib/ir/instructions.cc",
        "lib/ir/metadata.cc",
        "lib/ir/module.cc",
        "lib/ir/print.cc",
        "lib/ir/type.cc",
        "lib/ir/utils.cc",
        "lib/ir/value.cc",
    ],
    hdrs = [
        "include/triton/ir/basic_block.h",
        "include/triton/ir/builder.h",
        "include/triton/ir/constant.h",
        "include/triton/ir/context.h",
        "include/triton/ir/context_impl.h",
        "include/triton/ir/enums.h",
        "include/triton/ir/function.h",
        "include/triton/ir/instructions.h",
        "include/triton/ir/metadata.h",
        "include/triton/ir/module.h",
        "include/triton/ir/print.h",
        "include/triton/ir/type.h",
        "include/triton/ir/utils.h",
        "include/triton/ir/value.h",
        "include/triton/ir/visitor.h",
    ],
    copts = [
        "-fexceptions",
        "-Wno-reorder-ctor",
    ],
    features = ["-use_header_modules"],
    includes = ["include"],
)

cc_library(
    name = "codegen",
    srcs = [
        "lib/codegen/analysis/align.cc",
        "lib/codegen/analysis/allocation.cc",
        "lib/codegen/analysis/axes.cc",
        "lib/codegen/analysis/layout.cc",
        "lib/codegen/analysis/liveness.cc",
        "lib/codegen/analysis/swizzle.cc",
        "lib/codegen/extern_lib.cc",
        "lib/codegen/pass.cc",
        "lib/codegen/selection/generator.cc",
        "lib/codegen/target.cc",
        "lib/codegen/transform/coalesce.cc",
        "lib/codegen/transform/cts.cc",
        "lib/codegen/transform/dce.cc",
        "lib/codegen/transform/disassociate.cc",
        "lib/codegen/transform/inline.cc",
        "lib/codegen/transform/membar.cc",
        "lib/codegen/transform/peephole.cc",
        "lib/codegen/transform/pipeline.cc",
        "lib/codegen/transform/prefetch.cc",
        "lib/codegen/transform/reorder.cc",
    ],
    hdrs = [
        "include/triton/codegen/analysis/align.h",
        "include/triton/codegen/analysis/allocation.h",
        "include/triton/codegen/analysis/axes.h",
        "include/triton/codegen/analysis/layout.h",
        "include/triton/codegen/analysis/liveness.h",
        "include/triton/codegen/analysis/swizzle.h",
        "include/triton/codegen/extern_lib.h",
        "include/triton/codegen/pass.h",
        "include/triton/codegen/selection/generator.h",
        "include/triton/codegen/target.h",
        "include/triton/codegen/transform/coalesce.h",
        "include/triton/codegen/transform/cts.h",
        "include/triton/codegen/transform/dce.h",
        "include/triton/codegen/transform/disassociate.h",
        "include/triton/codegen/transform/inline.h",
        "include/triton/codegen/transform/membar.h",
        "include/triton/codegen/transform/peephole.h",
        "include/triton/codegen/transform/pipeline.h",
        "include/triton/codegen/transform/prefetch.h",
        "include/triton/codegen/transform/reorder.h",
    ],
    copts = [
        "-fexceptions",
        "-Wno-error",
        "-Wno-non-virtual-dtor",
        "-Wno-reorder-ctor",
        "-Wno-unused-variable",
        "-Wno-braced-scalar-init",
    ],
    features = ["-use_header_modules"],
    includes = ["include"],
    deps = [
        ":ir",
        ":tools",
        "@llvm-project//llvm:Core",
        "@llvm-project//llvm:IPO",
        "@llvm-project//llvm:IRReader",
        "@llvm-project//llvm:Linker",
        "@llvm-project//llvm:Support",
        "@llvm-project//llvm:TransformUtils",
    ],
)
